### ISSUE TITLE
Delete blog is not working 

### ISSUE THREAD

**Issue by khushi2706** [khushi2706/Blog-App-using-MERN-stack#1]

**Comment by swtbhsmn** [comment]
## Issue found :
```
{blogs &&
        blogs.map((blog, index) => (
          <Blog
            id={blog._id}
            isUser={localStorage.getItem("userId") === blog.user._id} // Always value of isUser is false
            title={blog.title}
            desc={blog.desc}
            img={blog.img}
            user={blog.user.name}
          />
))}
```
## Explanation
* Data looks like this for ```blog``` : { "_id": "63bb9871feda215df5b1c287", "title": "xyz", "desc": "issue.", "img": "image_url", "user": "63bb782b7db0d507fa04bd69", "__v": 0 } 
* blog.user is type of string not object ```blog.user.id``` 

## Resolve
> Replace this line {localStorage.getItem("userId") === blog.user._id}  to ```{localStorage.getItem("userId") === blog.user} ```

**Comment by Vyomrana02** [comment]
Hello @khushi2706 can u asign this issue to me I can fix this.

**Comment by rohity20** [comment]
The existing code contains an error in the delete blog API, causing issues with the blog deletion functionality. I have implemented the following changes to rectify this issue.

const deleteBlog = async (req, res, next) => {
    const id = req.params.id;

    try {
        const blog = await Blog.findByIdAndDelete(id).populate('user');

        if (!blog) {
            return res.status(404).json({ message: "Blog not found" });
        }

        // Remove the blog from the user's blogs array
        const user = blog.user;
        user.blogs.pull(blog);
        await user.save();

        return res.status(200).json({ message: "Successfully deleted" });
    } catch (e) {
        console.error(e);
        return res.status(500).json({ message: "Unable to delete" });
    }
}
